### ISSUE TITLE
Follower count bug 

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#134] opened 2017-10-26 18:22 UTC
It says I have one follower but when I make the fetch followers request it gives me two people

<img width="302" alt="screen shot 2017-10-26 at 2 21 14 pm" src="https://user-images.githubusercontent.com/14966713/32070034-fb719b00-ba58-11e7-9c31-875433841663.png">
<img width="229" alt="screen shot 2017-10-26 at 2 21 18 pm" src="https://user-images.githubusercontent.com/14966713/32070035-fc54551c-ba58-11e7-864f-c5871f01e449.png">
<img width="598" alt="screen shot 2017-10-26 at 2 21 08 pm" src="https://user-images.githubusercontent.com/14966713/32070037-fd56d5f2-ba58-11e7-8c22-72f97aa9dac9.png">
<img width="247" alt="screen shot 2017-10-26 at 2 20 38 pm" src="https://user-images.githubusercontent.com/14966713/32070040-fe5eb85c-ba58-11e7-8f34-8e927ac29cfb.png">

**Comment by ChenJesse** [comment] 2017-10-26 20:48
So I was looking at this bug a few weeks ago, but couldn't manage to reproduce it. Do you guys have any more information on how this occurred? I'll take another look by Sunday regardless

One of my suspicions is that this may have been caused by an earlier bug that we have fixed since, but now the db follower/following counts have been permanently messed up since.

**Comment by Jma353** [comment] 2017-11-02 00:47
Looks like this was merged in.  Closing.

**Closed as completed by Jma353** 2017-11-02 00:47 UTC
